export const CHANGE_INPUT_FIELD = "CHANGE_INPUT_FIELD";
export const CHANGE_PASSWORD_FIELD = "CHANGE_PASSWORD_FIELD";
export const UPDATE_CHECKBOX_STATUS = "UPDATE_CHECKBOX_STATUS";
export const GET_FORM_VALUE = "GET_FORM_VALUE";
